apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: yashvi-csr
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JUQ0NBVlVDQVFBd0tERVBNQTBHQTFVRUF3d0dlV0Z6YUhacE1SVXdFd1lEVlFRS0RBeGtaWFp2Y0hOdQpZMnh2ZFdRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNWdEd6NThnTlNHSTFGCmZLbHJsVldwdmlZOVVKUURicno0SWNiSHVSTGZjZjc2ZzdaRjEwVDQ5WXNHSTZXc1dsalJXMGVoVjBHcXBRWW8KSWpSZUV2R3NjS0w4L1R5ajdkeThpdGpSZzEzZVRaSXlWSTFxRGMzZ3Y1ekV0M1JPOWdoYWtpUW5iK2hFZHRDZQp1czc2KytYTDNUOFVNb2JwN2QveHlRakU1RWtlYXl0U0dnZllqTTF4QW0zdVZwQU1HU0o4QnpVeEhxWWkrMUlMCmhJbmRYdG5ic29PZWFreWxybE9IVXVBdU5DMFFZZzNraTE0aFA2c2kzWFg4TnNTeVl4LzJTMXFwcWNMK0doM3MKaUt1YXg5RVBLcklha3hiVHRJVlF5c3dwRHJmdExoT1NMZkI1QXdNaXY2SmxVamc0clRlcDJ6UFdKb3FyN1hmZgpxdU9ROUNSZEFnTUJBQUdnQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUFvQmlvMERXU1RPOUtBQllYRk1mCjQvUExBa0krR2VrVWFmL3R0cXFRZWM0NG50RERQNWNGT1Q4cUQ4eG9vUzc3U09EcTlrZkxOSlRYeXV2UVRvNHAKK1JKVzBLSXlDSStPK2c3VFJ1M0sxV2E3RGtaOE1CbE5Fa3ppdmhvckVnaXlQeWRZTC9vZ3Rpek1OMVlWWUlKcwozd0xGN20zQ2Z3T3pOT1V1V1g1aDYrMExoajNMYWkwU3ZOQ0FrQXRFQWhNOEZNRGZkVTdzYmVVeTJUTkhkN1Y1CkFYOGN1clR6NGlBd0tnUHVEa2NzYXQ3V2VYQ2pnUHprTHZnQSt6YkRNUHhWditUaEZMTVd2amJKMWd2TEVKc0cKUzJaRnA2bW84a042UUI1b3hBZFhQclNYNk4rb1ZsaStRTDlzb3VNNlNidlFHNEVvTThrTzdjT2hCUWxQK1BjSQo4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - client auth

