apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    apptype: frontend
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
      apptype: frontend
  template:
    metadata:
      labels:
        env: prod
        apptype: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
