apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: readiness
  name: readiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - name: readiness
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - cat
            - /var/healthyfile1
          failureThreshold: 3
