apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "lowspec"
    effect: "NoSchedule"

