apiVersion: v1
kind: Pod
metadata:
  name: web15
  labels:
    env: dev
    apptype: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    hardware: lowspec 
